### ISSUE TITLE
Bad output sound quality

### ISSUE THREAD

**Issue by BitBlueDevStudio** [sony/ai-research-code#32]
I noticed that output quality is much worse than in input file. Maybe there is some config, which cuts some frequencies from output file? 

In spleeter there is issue like that, which can be resolved with simply config change.

Both pretrained models (openvino and default) provide same bad quality. Sounds like high frequencies are cutted off.

Thanks in advance!

**Comment by JX-HuaDing** [comment]
@BitBlueDevStudio

We tried to reproduce this problem in music-source-separation project, using the following command:
'''
/ > python separate.py -i test.wav -m ./models/d3net-mss.h5
'''

the test.wav was converted from xxx.mp4 by the following command:
'''
/ > ffmpeg -i xxx.mp4 -ac 2 -f wav test.wav
'''

Above xxx.mp4 file came from MUSDB18 dataset, you could download it from the following url:
'''
https://zenodo.org/record/1117372#.YUQ3FHUzbJU
'''

d3net-mss.h5 was the pretrained model, you could download it from the following url:
'''
https://nnabla.org/pretrained-models/ai-research-code/d3net/mss/d3net-mss.h5
'''

we got the output file and the quality of it was ok, we couldn't get this phenomenon that high frequencies were cutted off in my output file. could you give me more detailed information (such as the project you used, the command you used, the dataset you used and the pretrained model you used) about your operating in this issue so that I could reproduce the problem further?

**Comment by TomonobuTsujikawa** [comment]
Thank you for reporting.

We tried to reproduce your issue using MUSDB18 dataset, but we cannot reproduce your issue as of now.
Would it be possible to share the audio file or URL with us?

Thanks!

**Comment by BitBlueDevStudio** [comment]
Hello! Thanks for reply.

I realized that if i combine drums/bass/other - I'll get track that quality is ok, but if I listen only "other" it sounds a little blurry, compared to demucs_extra result for example. But demucs_extra has ther own problems  ))

It looks like more upper frequencies going to drums, I'll try to provide example files later
